CREATE TABLE Users (
    USER_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    USER_PASSWORD VARCHAR(255),
    EMAIL VARCHAR(255),
    DOB DATE
);

CREATE TABLE UserContacts (
    CONTACT_ID INT PRIMARY KEY,
    USER_ID INT,
    ADDRESS VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);

CREATE TABLE UserAccounts (
    ACCOUNT_ID INT PRIMARY KEY,
    USER_ID INT,
    ACCOUNT_NUMBER VARCHAR(50),
    ACCOUNT_TYPE VARCHAR(50),
    BALANCE DECIMAL(12,2),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);


CREATE TABLE UserStatus (
    USER_ID INT PRIMARY KEY,
    STATUS VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);